nameOverride: argo-cd
global:
  domain: argocd.tuan-lnm.org

redis-ha:
  enabled: false

configs:
  rbac:
    policy.csv: |
      g, engineering, role:admin

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
  extraArgs:
  - --insecure

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2

applicationSet:
  replicas: 1
  

