apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.vault.svc:8200" # Internal URL
      path: "secret"
      version: "v2"
      caBundle: ""
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "cert-manager" 
          serviceAccountRef:
              name: cert-manager
              namespace: cert-manager