image:
  # -- The Docker registry
  registry: docker.io
  # -- Docker image repository
  repository: grafana/promtail
  # -- Overrides the image tag whose default is the chart's appVersion
  tag: 3.6.3
  # -- Docker image pull policy
  pullPolicy: IfNotPresent

config:
  clients:
    - url: http://loki-logging-gateway:80/loki/api/v1/push